#server:
#  port: 8081
#
#spring:
#  application:
#    name: product-service
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/humble_product
#    username: postgres
#    password: amal1234
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
## Configuration pour le stockage des images
#image:
#  upload-dir: ./uploads/images

